### ISSUE TITLE
Send PR to PostCSS README

### ISSUE THREAD

**Issue by ai** [totora0155/postcss-namespace#1]

**Comment by simonsmith** [comment]
Such a plugin already exists - https://github.com/thompsongl/postcss-class-prefix

**Comment by ai** [comment]
@simonsmith nope. In `postcss-class-prefix` you set prefix in JS and here you set it directly in CSS

**Comment by simonsmith** [comment]
Fair enough. However it's worth noting that `@namespace` already exists as part of the CSS spec:

https://developer.mozilla.org/en-US/docs/Web/CSS/@namespace

**Comment by ai** [comment]
@simonsmith yeap :(. Please, create a spearated issue.

**Comment by simonsmith** [comment]
:+1:

**Comment by totora0155** [comment]
oh...
About that, I didn't know until now :flushed:

@ai @simonsmith 
Thank you so much!
